import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Page_Name from './pagename';
import Header from './components/header';
import Footer from './components/footer';


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
//   return (
//     <html lang="en">
//       <div className="site">
//         <Page_Name/>
//         <body className={inter.className}>
//           <Header/>
//           {children}
//           <Footer/>
//         </body>
//       </div>
//     </html>
//   );
// }
    return(
      <html>
        <body>
          <Header/>
          <Footer/>
        </body>
      </html>
  );
};